spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: atatat
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Hello Second API!!

---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: atatat
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Hello Second API!!
---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: atatat
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
welcome:
  message: Hello Second API!!

---

server:
  port: '8082'

spring:
  profiles:
    active: qa

